from functools import partial
import os
import time

def pause():
    time.sleep(1)
pause()

def end():
    time.sleep(30)
end()    

root = os.getcwd()
concat = partial(os.path.join, root)
make = partial(os.makedirs, exist_ok=True)

Artists = [
    'Artists/Dacad',
    'Artists/Tokifuji',
    'Artists/MarsMiner',
    'Artists/Domas',
    'Artists/thericegoat',
    'Artists/Stupid Furry',
    'Artists/pomopuchi',
    'Artists/Frumples',
    'Artists/Castitas',
    'Artists/Camotli',
    'Artists/Eipril',
    'Artists/Seibrxan',
    'Artists/Up1ter',
    'Artists/Zäcky',
    'Artists/Spaal',
    'Artists/Naika',
    'Artists/wizzikt',
    'Artists/Breaburned',
    'Artists/Dagasi',
    'Artists/tarantuloo',
    'Artists/eto ya',
    'Artists/ombwie',
    'Artists/ivnis',
    'Artists/DoeBoi',
    'Artists/Desertkaiju',
    'Artists/Coffeesoda',
    'Artists/ssssnowy',
    'Artists/Fizzystevie',
    'Artists/sukendo',
    'Artists/mabit',
    'Artists/pawpadcomrade',
    'Artists/fureezy',
    'Artists/clade',
    'Artists/fassie',
    'Artists/Roy arashi',
    'Artists/Fuzzamorous',
    'Artists/nasty-pink',
    'Artists/oro97',
    'Artists/Rajii',
    'Artists/jumpy jackal',
    'Artists/bluedeluge',
    'Artists/eneirem',
    'Artists/mintyfreshtea',
    'Artists/enokimaru',
    'Artists/batartcave',
    'Artists/edjit',
    'Artists/captainskee',
    'Artists/ses vanbrubles',
    'Artists/pocketpaws',
    'Artists/dragontim',
    'Artists/xeono',
    'Artists/km-15',
    'Artists/saltyxodium',
    'Artists/drmax',
    'Artists/zaush',
    'Artists/syuro',
    'Artists/trigaroo',
    'Artists/sigma x',
    'Artists/mykendyke',
    'Artists/justmegabenewell',
    'Artists/theobrobine',
    'Artists/sethpup',
    'Artists/taga',
    'Artists/mao.j',
    'Artists/bilebubble',
    'Artists/codyblue-731',
    'Artists/ruaidri',
    'Artists/whygena',
    'Artists/upov',
    'Artists/zoruken',
    'Artists/k 98',
    'Artists/gobanire',
    'Artists/zonkpunch',
    'Artists/melieconiek',
    'Artists/whisperingfornothing',
    'Artists/etheross',
    'Artists/haltie',
    'Artists/diives',
    'Artists/shinodage',
    'Artists/hooves-art',
    'Artists/r-mk',
    'Artists/bnbigus',
    'Artists/pikajota',
    'Artists/cervina7',
    'Artists/sukendo',
    'Artists/tofu froth',
    'Artists/loimu',
    'Artists/brolaren',
    'Artists/itomic',
    'Artists/squealydealy',
    'Artists/shirokoma',
    'Artists/miso souperstar',
    'Artists/oughta',
    'Artists/dengon',
    'Artists/deepstroke',
    'Artists/whisperfoot',
    'Artists/akamu ver20',
    'Artists/komdog',
    'Artists/zero-sum',
    'Artists/strayserval',
    'Artists/healingpit',
    'Artists/fluff-kevlar',
    'Artists/anglo',
    'Artists/photonoko',
    'Artists/meesh',
    'Artists/ashrealy',
    'Artists/bikomation',
    'Artists/ratatooey',
    'Artists/snowskau',
    'Artists/phenyanyanya',
    'Artists/vksuika',
    'Artists/skully',
    'Artists/twitchyanimation',
    'Artists/jakethegoat',
    'Artists/butterchalk',
    'Artists/seff',
    'Artists/burgerkiss',
    'Artists/jizoku',
    'Artists/canaryprimary',
    'Artists/alfa995',
    'Artists/claweddrip',
    'Artists/feliscede',
    'Artists/reysi',
    'Artists/keadonger',
    'Artists/ttothep arts',
    'Artists/thescarletdragon1',
    'Artists/riska',
    'Artists/pudgeruffian',
    'Artists/metal',
    'Artists/prsmrti',
    'Artists/thousandfoldfeathers',
    'Artists/demimond23',
    'Artists/chelodoy',
    'Artists/evomanaphy',
    'Artists/masterploxy',
    'Artists/kekitopu',
    'Artists/cobatsart',
    'Artists/hioshiru',
    'Artists/kejifox',
    'Artists/youwannaslap',
    'Artists/personalami',
    'Artists/nuzzo',
    'Artists/totesfleisch8',
    'Artists/snuckums',
    'Artists/patto',
    'Artists/drako1997',
    'Artists/usnarbit',
    'Artists/raaz',
    'Artists/smitty g',
    'Artists/seraziel',
    'Artists/htpot',
    'Artists/wolfy-nail',
    'Artists/sollyz',
    'Artists/loonanudes',
    'Artists/wizardlywalrusking',
    'Artists/underscore b',
    'Artists/mintyspirit',
    'Artists/danonymous',
    'Artists/jishinu',
    'Artists/evenesko.d.fox',
    'Artists/sususuigi',
    'Artists/dragk',
    'Artists/nnecgrau',
    'Artists/wamudraws',
    'Artists/dimwitdog',
    'Artists/nikkibunn',
    'Artists/twiren',
    'Artists/borvar',
    'Artists/theblueberrycarrots',
    'Artists/danomill',
    'Artists/utopianvee',
    'Artists/merunyaa',
    'Artists/elicitie',
    'Artists/enginetrap',
    'Artists/juantriforce',
    'Artists/samur shalem',
    'Artists/goolee',
    'Artists/zeameari',
    'Artists/ittybittykittytittys',
    'Artists/twinkle-sez',
    'Artists/kisera',
    'Artists/the dogsmith',
    'Artists/xennos',
    'Artists/trinity-fate62',
    'Artists/rmtwo',
    'Artists/avante92',
    'Artists/rainbowscreen',
    'Artists/woolrool',
    'Artists/orange-peel',
    'Artists/phallusbro',
    'Artists/siroc',
    'Artists/discreet user',
    'Artists/dobrota',
    'Artists/kittydee',
    'Artists/sugarlesspaints',
    'Artists/dark violet',
    'Artists/pakwan008',
    'Artists/hladilnik',
    'Artists/colonelyobo',
    'Artists/fumiko',
    'Artists/starit',
    'Artists/greasymojo',
    'Artists/hale',
    'Artists/gewitter',
    'Artists/princess hinghoi',
    'Artists/dr.bubblebum',
    'Artists/scappo',
    'Artists/romarom',
    'Artists/rysonanthrodog',
    'Artists/paperclip',
    'Artists/atrolux',
    'Artists/tsampikos',
    'Artists/black-kitten',
    'Artists/singafurian',
    'Artists/funkybun',
    'Artists/steel cat',
    'Artists/twistedhound',
    'Artists/iwbitu',
    'Artists/moth sprout',
    'Artists/carrot',
    'Artists/valkoinen',
    'Artists/zeiro',
    'Artists/zoyler',
    'Artists/sonsasu',
    'Artists/nowandlater',
    'Artists/letodoesart',
    'Artists/xnirox',
    'Artists/naive tabby',
    'Artists/f-r95',
    'Artists/jay-r',
    'Artists/kyrosh',
    'Artists/chano',
    'Artists/trevart',
    'Artists/sidnithefox',
    'Artists/nitani',
    'Artists/zawmg',
    'Artists/bassenji',
    'Artists/senimasan',
    'Artists/redcreator',
    'Artists/roanoak',
    'Artists/tentabat',
    'Artists/meraence',
    'Artists/pinkaxoloti',
    'Artists/jailbird',
    'Artists/thesecretcave',
    'Artists/glopossum',
    'Artists/castbound',
    'Artists/lemeonlemeon',
    'Artists/demicoeur',
    'Artists/daxhush',
    'Artists/tyroo',
    'Artists/captainzepto',
    'Artists/sinfulwhispers15',
    'Artists/redfeatherstorm',
    'Artists/sabuky',
]